# General provisioning
- name: Update packages
  apt:
    update_cache: yes

- name: Upgrade Ubuntu
  apt:
    upgrade=dist
    force_apt_get=yes

- name: Install favourite text editor neovim
  apt:
    name: neovim
    state: present

- name: Install git
  apt:
    name: git
    state: present

- name: Set up authorised ssh key
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ user_pub_key }}"

- name: Ensure group "wheel" exists
  group:
    name: wheel
    state: present

- name: Ensure group "sudo" exists
  group:
    name: sudo
    state: present

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Create non-root sudo user
  user: "{{ username }}"
  password: "{{ user_password }}"
  shell: /bin/bash
  groups:
    - wheel
    - sudo
    - docker

- name: Allow 'wheel' group users to use passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    become: yes

- name: allow or disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    backup: yes

- name: disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    backup: yes
  notify: restart ssh service

- name: enable ssh service
  ansible.builtin.service:
    name: sshd
    enabled: yes

handlers:
  - name: restart sshd service
    ansible.builtin.service:
      name: sshd
      state: restarted
