# Setup docker
- name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

 - name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Let a user run docker without sudo
  become: yes
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
    state: present

- name: Ensure docker deamon is running
  ansible.builtin.service:
    name: docker
    state: started

- name: Ensure docker deamon is enable
  ansible.builtin.service:
    name: docker
    state: enabled